spring:
  profiles:
    active: local
# http服务、信息统计页面入口
server:
  port: 30000
  compression:
    enabled: true
    min-response-size: 512
gateway:
  enable: true
  access-type: tcp
  port: 30000
  notification: # 元数据事件通知，如连接、登陆、发送、接收、关闭
    - type: kafka
      topic: {
        connect: "connect",
        login: "login",
        send: "send",
        receive: "receive",
        close: "close",
      }
    - type: redis
      topic: {
        connect: "connect",
        login: "login",
        send: "send",
        receive: "receive",
        clos: "close",
      }
  dispatch:
    type: kafka # 解析数据分发策略，默认spring内部通知
    topic: dispatch-topic # 解析数据分发策略，默认spring内部通知
  send:
    type: kafka
    topic: send_down

  parameter: {
    protocol: abc, # 对应的解析协议，第一个handler应该是分包handler
    login_timeout: 0, # 登陆超时，单位:秒
    heart_timeout: 0 # 心跳超时，单位:秒
  }

#  udp:
#    enable: true
#    port: 31000
#    parameter: {
#      protocol: abc # udp不需要分包handler,但是可能需要其他控制类handler
#      login_timeout: 60 # 登陆超时，单位:秒
#      heart_timeout: 600 # 心跳超时，单位:秒
#    }
#  http:
#    enable: true
#    port: ${server.port}
#    parameter: {
#
#    }
#  mqtt:
#    enable: true
#    port: 32000
#    parameter: {
#
#    }
#  websocket:
#    enable: true
#    port: 33000
#    parameter: {
#    }
logging:
  level:
    com.jfeng.gateway*: debug

