spring:
  server:
    port: 9999
  kafka:
    bootstrap-servers:  192.168.40.105:9092,192.168.40.106:9092,192.168.40.107:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: access
  redis:
    database: 0
    host: 192.168.40.56
    port: 6379
    timeout: 30000
gateway:
  enable: true
  port: 30003
  dstTopic: tcp_topic # 转发目的地
  parameter: {
    protocol: abc, # 对应的解析协议，第一个handler应该是分包handler
    login_timeout: 0, # 登陆超时，单位:秒
    heart_timeout: 0 # 心跳超时，单位:秒
  }
