spring:
  profiles:
    active: prod
server:
  port: 9999
  compression:
    enabled: true
    min-response-size: 512
gateway:
  enable: true
  port: 30003
  dstTopic: tcp_topic # 转发目的地
  parameter: {
    protocol: abc, # 对应的解析协议，第一个handler应该是分包handler
    login_timeout: 0, # 登陆超时，单位:秒
    heart_timeout: 0 # 心跳超时，单位:秒
  }
