server:
  port: 9000
  compression:
    enabled: true
    min-response-size: 512
spring:
  kafka:
    bootstrap-servers:  127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: iot-gateway-1
  redis:
    enable: true
    host: 127.0.0.1
    port: 6379
    timeout: 30000
gateway:
  enable: true
  port: 30000
  dstTopic: tcp_topic # 转发目的地
  parameter: {
    protocol: abc, # 对应的解析协议，第一个handler应该是分包handler
    login_timeout: 0, # 登陆超时，单位:秒
    heart_timeout: 0 # 心跳超时，单位:秒
  }
